sylius_grid:
    grids:
        tavy315_sylius_labels_admin_label:
            driver:
                options:
                    class: "%tavy315_sylius_labels.model.label.class%"
            fields:
                code:
                    type: string
                    label: tavy315_sylius_labels.ui.code
                    sortable: ~
                name:
                    type: string
                    label: tavy315_sylius_labels.ui.name
                    sortable: ~
            filters:
                name:
                    type: string
                    label: tavy315_sylius_labels.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
